/**
 * Core Types for Multi-Agent Enrichment System
 *
 * These types define the contract between agents, tools, and the orchestrator.
 */

// ============ Enrichment Fields ============

/**
 * All possible enrichment fields the system can handle.
 */
export type EnrichmentFieldKey =
    | "name"
    | "company"
    | "email"           // Primary verified email
    | "emailCandidates" // List of candidate emails
    | "title"
    | "shortBio"
    | "socialLinks"
    | "companySize"
    | "location"
    | "companySummary"
    | "whois"
    | "techStack"
    | "funding"
    | "foundedDate"
    | "industry"        // Company industry/sector
    | "linkedinUrl"     // LinkedIn profile URL
    | "domain";         // Company domain

/**
 * Tier classification for providers.
 * Used to control cost and ordering in the waterfall.
 */
export type ProviderTier = "free" | "cheap" | "premium";

/**
 * Confidence level for enriched values.
 * 0 = no confidence, 1 = absolute certainty.
 */
export type Confidence = number; // 0..1

// ============ Provider Results ============

/**
 * Result from a single provider call.
 */
export interface ProviderResult {
    field: EnrichmentFieldKey;
    value: string | number | string[] | null;
    raw?: unknown; // Original provider response for debugging
    confidence: Confidence;
    source: string; // Provider name
    costCents?: number;
    timestamp: string;
    verified?: boolean; // For emails
}

/**
 * Provenance record for audit trail.
 */
export interface Provenance {
    source: string;
    timestamp: string;
    confidence: Confidence;
    rawValue?: unknown;
    field: EnrichmentFieldKey;
}

/**
 * Canonical data for a row after reconciliation.
 */
export interface CanonicalData {
    [field: string]: {
        value: string | number | string[] | null;
        confidence: Confidence;
        source: string;
        verified?: boolean;
    };
}

// ============ Enrichment Input ============

/**
 * Normalized input for enrichment.
 */
export interface NormalizedInput {
    rowId: string;
    tableId: string;
    name?: string;
    domain?: string;
    linkedinUrl?: string;
    email?: string;
    company?: string;
    raw: Record<string, unknown>;
}

// ============ Planner Types ============

/**
 * A single step in the enrichment plan.
 */
export interface PlanStep {
    step: number;
    tool: string;
    field: EnrichmentFieldKey;
    providerName?: string;
    priority: "high" | "medium" | "low";
    maxCostCents?: number;
}

/**
 * The execution plan generated by the Concierge agent.
 */
export interface EnrichmentPlan {
    plan: PlanStep[];
    maxCostCents: number;
    notes?: string;
}

// ============ Provider Interface ============

/**
 * Interface that all provider tools must implement.
 */
export interface ProviderToolInterface {
    name: string;
    tier: ProviderTier;
    costCents: number;

    /**
     * Check if this provider can enrich a given field.
     */
    canEnrich(field: EnrichmentFieldKey): boolean;

    /**
     * Execute the enrichment.
     */
    enrich(input: NormalizedInput, field: EnrichmentFieldKey): Promise<ProviderResult | null>;
}

// ============ Workflow Context ============

/**
 * Context passed through the enrichment workflow.
 */
export interface EnrichmentWorkflowContext {
    input: NormalizedInput;
    plan?: EnrichmentPlan;
    evidence: ProviderResult[];
    canonical?: CanonicalData;
    provenance: Provenance[];
    costCentsTotal: number;
    status: "pending" | "processing" | "completed" | "failed" | "ambiguous";
    errors: string[];
}

// ============ Source Weights ============

/**
 * Weights for different sources used in reconciliation.
 * Higher weight = more trusted source.
 */
export const SOURCE_WEIGHTS: Record<string, number> = {
    linkedin_api: 0.95,
    hunter: 0.9,
    open_corporates: 0.95,
    github: 0.9,
    whois: 0.85,
    serp: 0.7,
    pattern_inference: 0.3,
    llm: 0.2,
    mock: 0.5, // For testing
};

// ============ Confidence Thresholds ============

/**
 * Minimum confidence required per field to consider it "good enough".
 */
export const CONFIDENCE_THRESHOLDS: Partial<Record<EnrichmentFieldKey, number>> = {
    name: 0.6,
    company: 0.6,
    emailCandidates: 0.5,
    title: 0.5,
    shortBio: 0.4, // LLM-generated, lower bar
    socialLinks: 0.5,
    companySize: 0.4,
    location: 0.5,
    companySummary: 0.4,
};

// ============ TTL Configuration ============

/**
 * Cache TTL in days for each field.
 */
export const FIELD_TTL_DAYS: Partial<Record<EnrichmentFieldKey, number>> = {
    name: 90,
    company: 60,
    emailCandidates: 14, // Emails change frequently
    title: 30,
    shortBio: 60,
    socialLinks: 30,
    companySize: 90,
    location: 60,
    companySummary: 90,
};
